import variants from './imageVariants.json'

/**
 * Builds a srcset string for a local /images/... webp from the variants
 * generated by `npm run images` (scripts/generate-image-variants.mjs).
 * Returns undefined for unknown paths (e.g. Sanity CDN URLs or images with
 * no smaller variants), so callers can pass any src safely — the browser
 * then just uses the plain src attribute.
 */
export function srcSet(src) {
  const meta = variants[src]
  if (!meta || meta.widths.length === 0) return undefined
  return [
    ...meta.widths.map((w) => `${src.replace(/\.webp$/i, `-${w}w.webp`)} ${w}w`),
    `${src} ${meta.w}w`,
  ].join(', ')
}
